class LM {
  static const Map t = {
    'PL' : {

      'ISO' : {
        'FLK' : "Falklandy",
        'AFG' : 'Afganistan',
        'ALB' : 'Albania',
        'DZA' : 'Algieria',
        'AND' : 'Andora',
        'AGO' : 'Angola',
        'ATG' : 'Antigua i Barbuda',
        'SAU' : 'Arabia Saudyjska',
        'ARG' : 'Argentyna',
        'ARM' : 'Armenia',
        'AUS' : 'Australia',
        'AUT' : 'Austria',
        'AZE' : 'Azerbejdżan',
        'BHS' : 'Bahamy',
        'BHR' : 'Bahrajn',
        'BGD' : 'Bangladesz',
        'BRB' : 'Barbados',
        'BEL' : 'Belgia',
        'BLZ' : 'Belize',
        'BEN' : 'Benin',
        'BTN' : 'Bhutan',
        'BLR' : 'Białoruś',
        'BOL' : 'Boliwia',
        'BIH' : 'Bośnia i Hercegowina',
        'BWA' : 'Botswana',
        'BRA' : 'Brazylia',
        'BRN' : 'Brunei',
        'BGR' : 'Bułgaria',
        'BFA' : 'Burkina Faso',
        'BDI' : 'Burundi',
        'CHL' : 'Chile',
        'CHN' : 'Chiny',
        'HRV' : 'Chorwacja',
        'CYP' : 'Cypr',
        'TCD' : 'Czad',
        'MNE' : 'Czarnogóra',
        'CZE' : 'Czechy',
        'DNK' : 'Dania',
        'COD' : 'Demokratyczna Republika Konga',
        'DMA' : 'Dominika',
        'DOM' : 'Dominikana',
        'DJI' : 'Dżibuti',
        'EGY' : 'Egipt',
        'ECU' : 'Ekwador',
        'ERI' : 'Erytrea',
        'EST' : 'Estonia',
        'SWZ' : 'Eswatini',
        'ETH' : 'Etiopia',
        'FJI' : 'Fidżi',
        'PHL' : 'Filipiny',
        'FIN' : 'Finlandia',
        'FRA' : 'Francja',
        'GRL' : 'Grenlandia',
        'GAB' : 'Gabon',
        'GMB' : 'Gambia',
        'GHA' : 'Ghana',
        'GRC' : 'Grecja',
        'GRD' : 'Grenada',
        'GEO' : 'Gruzja',
        'GUY' : 'Gujana',
        'GTM' : 'Gwatemala',
        'GNB' : 'Gwinea Bissau',
        'GNQ' : 'Gwinea Równikowa',
        'GIN' : 'Gwinea',
        'HTI' : 'Haiti',
        'ESP' : 'Hiszpania',
        'NLD' : 'Holandia',
        'HND' : 'Honduras',
        'IND' : 'Indie',
        'IDN' : 'Indonezja',
        'IRQ' : 'Irak',
        'IRN' : 'Iran',
        'IRL' : 'Irlandia',
        'ISL' : 'Islandia',
        'ISR' : 'Izrael',
        'JAM' : 'Jamajka',
        'JPN' : 'Japonia',
        'YEM' : 'Jemen',
        'JOR' : 'Jordania',
        'KHM' : 'Kambodża',
        'CMR' : 'Kamerun',
        'CAN' : 'Kanada',
        'QAT' : 'Katar',
        'KAZ' : 'Kazachstan',
        'KEN' : 'Kenia',
        'KGZ' : 'Kirgistan',
        'KIR' : 'Kiribati',
        'COL' : 'Kolumbia',
        'COM' : 'Komory',
        'COG' : 'Kongo',
        'KOR' : 'Korea Południowa',
        'PRK' : 'Korea Północna',
        'CRI' : 'Kostaryka',
        'CUB' : 'Kuba',
        'KWT' : 'Kuwejt',
        'LAO' : 'Laos',
        'LSO' : 'Lesotho',
        'LBN' : 'Liban',
        'LBR' : 'Liberia',
        'LBY' : 'Libia',
        'LIE' : 'Liechtenstein',
        'LTU' : 'Litwa',
        'LUX' : 'Luksemburg',
        'LVA' : 'Łotwa',
        'MKD' : 'Macedonia Północna',
        'MDG' : 'Madagaskar',
        'MWI' : 'Malawi',
        'MDV' : 'Malediwy',
        'MYS' : 'Malezja',
        'MLI' : 'Mali',
        'MLT' : 'Malta',
        'MAR' : 'Maroko',
        'MRT' : 'Mauretania',
        'MUS' : 'Mauritius',
        'MEX' : 'Meksyk',
        'FSM' : 'Mikronezja',
        'MMR' : 'Mjanma',
        'MDA' : 'Mołdawia',
        'MCO' : 'Monako',
        'MNG' : 'Mongolia',
        'MOZ' : 'Mozambik',
        'NAM' : 'Namibia',
        'NRU' : 'Nauru',
        'NPL' : 'Nepal',
        'DEU' : 'Niemcy',
        'NER' : 'Niger',
        'NGA' : 'Nigeria',
        'NIC' : 'Nikaragua',
        'NOR' : 'Norwegia',
        'NZL' : 'Nowa Zelandia',
        'OMN' : 'Oman',
        'PAK' : 'Pakistan',
        'PLW' : 'Palau',
        'PAN' : 'Panama',
        'PNG' : 'Papua-Nowa Gwinea',
        'PRY' : 'Paragwaj',
        'PER' : 'Peru',
        'POL' : 'Polska',
        'PRT' : 'Portugalia',
        'ZAF' : 'Południowa Afryka',
        'CAF' : 'Republika Środkowoafrykańska',
        'CPV' : 'Republika Zielonego Przylądka',
        'RUS' : 'Rosja',
        'ROU' : 'Rumunia',
        'RWA' : 'Rwanda',
        'KNA' : 'Saint Kitts i Nevis',
        'LCA' : 'Saint Lucia',
        'VCT' : 'Saint Vincent i Grenadyny',
        'SLV' : 'Salwador',
        'WSM' : 'Samoa',
        'SMR' : 'San Marino',
        'SEN' : 'Senegal',
        'SRB' : 'Serbia',
        'SYC' : 'Seszele',
        'SLE' : 'Sierra Leone',
        'SGP' : 'Singapur',
        'SVK' : 'Słowacja',
        'SVN' : 'Słowenia',
        'SOM' : 'Somalia',
        'LKA' : 'Sri Lanka',
        'USA' : 'Stany Zjednoczone',
        'SDN' : 'Sudan',
        'SSD' : 'Sudan Południowy',
        'SUR' : 'Surinam',
        'SYR' : 'Syria',
        'CHE' : 'Szwajcaria',
        'SWE' : 'Szwecja',
        'TJK' : 'Tadżykistan',
        'THA' : 'Tajlandia',
        'TZA' : 'Tanzania',
        'TLS' : 'Timor Wschodni',
        'TGO' : 'Togo',
        'TON' : 'Tonga',
        'TTO' : 'Trynidad i Tobago',
        'TUN' : 'Tunezja',
        'TUR' : 'Turcja',
        'TKM' : 'Turkmenistan',
        'TUV' : 'Tuvalu',
        'UGA' : 'Uganda',
        'UKR' : 'Ukraina',
        'URY' : 'Urugwaj',
        'UZB' : 'Uzbekistan',
        'VUT' : 'Vanuatu',
        'VEN' : 'Wenezuela',
        'HUN' : 'Węgry',
        'GBR' : 'Wielka Brytania',
        'VNM' : 'Wietnam',
        'ITA' : 'Włochy',
        'CIV' : 'Wybrzeże Kości Słoniowej',
        'MHL' : 'Wyspy Marshalla',
        'SLB' : 'Wyspy Salomona',
        'STP' : 'Wyspy Świętego Tomasza i Książęca',
        'ZMB' : 'Zambia',
        'ZWE' : 'Zimbabwe',
        'ARE' : 'Zjednoczone Emiraty Arabskie',
      },
      'TC' : "Łączna liczba przypadków",
      'NC' : "Nowe przypadki",
      'TCPM' : "Przypadki na milion",
      'MODE' : "Wybierz tryb mapy",
      'INFO' : 'O nas',
      'US' : 'Miłosz Wardyła - dyrektor kreatywny\nIgor Urbanik - koder\nMateusz Konieczny - artysta',
      'HH' : 'Aplikacja stworzona na projekt HackHeroes 2020.',
      'TIP' : 'Porady',
      'TIP1' : 'Pamiętaj o noszeniu maseczki w miejscach publicznych, zgodnie z zaleceniami zdrowotnymi w twoim kraju. Maseczka zmniejsza prawdopodobieństwo zarażenia innych osób gdyby noszący był zarażony. Pamiętaj aby zakrywac i usta i nos!',
      'TIP2' : 'Dezynfekowanie rąk jest bardzo ważne, ponieważ nieświadomie dotykamy wiele różnych powierzni w sklepach, parkach itd., a nigdy nie wiadomo kto wcześniej robił to samo. Więc pamiętaj aby dezynfekować je zawsze gdy robisz coś na zewnątrz czy gdy po prostu wracasz do domu.',
      'TIP3' : 'Oprócz używania płynów dezynfekujących ważne jest również porządne mycie rąk. Wystarczy 20-30 sekund aby pozbyć się większości wirusów i bakterii z dłoni i zapewnić sobie i innym większe bezpieczeństwo.',
      'TIP4' : 'Używaj karty płatniczej zamiast gotówki w sklepach, restauracjach itd. Tak postępując ograniczasz niepotrzebny kontakt i zmniejszasz ryzyko zakażenia. ',
      'TIP5' : 'W czasach pandemii staraj się nie wychodzic z domu chyba, że jest to konieczne. Unikaj dużych zbiorowisk, nie chodź na i nie organizuj imprez. Dla dobra swojego i otoczenia: Zostań w domu!',
      'TIP6' : 'Zachowaj od innych odstęp conajmniej 2 metrów gdy poruszasz się w przestrzeni publicznej i gdy używasz środków komunikacji. Tak postępując zmniejszasz ryzyko rozprzestrzeniania się wirusa.',
      'TIP1T' : 'Maseczka',
      'TIP2T' : 'Dezynfekcja rąk',
      'TIP3T' : 'Mycie rąk',
      'TIP4T' : 'Karta lepsza od gotówki',
      'TIP5T' : 'Zostań w domu, ratuj życia.',
      'TIP6T' : 'Dystans społeczny',
      'DATA' : 'Dane od Our World In Data',

    },

    'EN' : {

      'ISO' : {
        'FLK' : "Falklands",
        'AFG' : "Afghanistan",
        'ALB' : "Albania",
        'DZA' : "Algeria",
        'AND' : "Andorra",
        'AGO' : "Angola",
        'ATG' : "Antigua and Barbuda",
        'ARG' : "Argentina",
        'ARM' : "Armenia",
        'AUS' : "Australia",
        'AUT' : "Austria",
        'AZE' : "Azerbaijan",
        'BHS' : "Bahamas",
        'BHR' : "Bahrain",
        'BGD' : "Bangladesh",
        'BRB' : "Barbados",
        'BLR' : "Belarus",
        'BEL' : "Belgium",
        'BLZ' : "Belize",
        'BEN' : "Benin",
        'BTN' : "Bhutan",
        'BOL' : "Bolivia",
        'BIH' : "Bosnia and Herzegovina",
        'BWA' : "Botswana",
        'BRA' : "Brazil",
        'BRN' : "Brunei Darussalam",
        'BGR' : "Bulgaria",
        'BFA' : "Burkina Faso",
        'BDI' : "Burundi",
        'CPV' : "Cabo Verde",
        'KHM' : "Cambodia",
        'CMR' : "Cameroon",
        'CAN' : "Canada",
        'CAF' : "Central African Republic",
        'TCD' : "Chad",
        'CHL' : "Chile",
        'CHN' : "China",
        'COL' : "Colombia",
        'COM' : "Comoros",
        'COG' : "Congo",
        'COD' : "DRC",
        'CRI' : "Costa Rica",
        'CIV' : "Côte d'Ivoire",
        'HRV' : "Croatia",
        'CUB' : "Cuba",
        'CYP' : "Cyprus",
        'CZE' : "Czechia",
        'DNK' : "Denmark",
        'DJI' : "Djibouti",
        'DMA' : "Dominica",
        'DOM' : "Dominican Republic",
        'ECU' : "Ecuador",
        'EGY' : "Egypt",
        'SLV' : "El Salvador",
        'GNQ' : "Equatorial Guinea",
        'ERI' : "Eritrea",
        'EST' : "Estonia",
        'SWZ' : "Eswatini",
        'ETH' : "Ethiopia",
        'FJI' : "Fiji",
        'FIN' : "Finland",
        'FRA' : "France",
        'GRL' : 'Greenland',
        'GAB' : "Gabon",
        'GMB' : "Gambia",
        'GEO' : "Georgia",
        'DEU' : "Germany",
        'GHA' : "Ghana",
        'GRC' : "Greece",
        'GRD' : "Grenada",
        'GTM' : "Guatemala",
        'GIN' : "Guinea",
        'GNB' : "Guinea-Bissau",
        'GUY' : "Guyana",
        'HTI' : "Haiti",
        'HND' : "Honduras",
        'HUN' : "Hungary",
        'ISL' : "Iceland",
        'IND' : "India",
        'IDN' : "Indonesia",
        'IRN' : "Iran",
        'IRQ' : "Iraq",
        'IRL' : "Ireland",
        'ISR' : "Israel",
        'ITA' : "Italy",
        'JAM' : "Jamaica",
        'JPN' : "Japan",
        'JOR' : "Jordan",
        'KAZ' : "Kazakhstan",
        'KEN' : "Kenya",
        'KIR' : "Kiribati",
        'PRK' : "North Korea",
        'KOR' : "South Korea",
        'KWT' : "Kuwait",
        'KGZ' : "Kyrgyzstan",
        'LAO' : "Lao People's Democratic Republic",
        'LVA' : "Latvia",
        'LBN' : "Lebanon",
        'LSO' : "Lesotho",
        'LBR' : "Liberia",
        'LBY' : "Libya",
        'LIE' : "Liechtenstein",
        'LTU' : "Lithuania",
        'LUX' : "Luxembourg",
        'MDG' : "Madagascar",
        'MWI' : "Malawi",
        'MYS' : "Malaysia",
        'MDV' : "Maldives",
        'MLI' : "Mali",
        'MLT' : "Malta",
        'MHL' : "Marshall Islands",
        'MRT' : "Mauritania",
        'MUS' : "Mauritius",
        'MEX' : "Mexico",
        'FSM' : "Micronesia",
        'MDA' : "Moldova",
        'MCO' : "Monaco",
        'MNG' : "Mongolia",
        'MNE' : "Montenegro",
        'MAR' : "Morocco",
        'MOZ' : "Mozambique",
        'MMR' : "Myanmar",
        'NAM' : "Namibia",
        'NRU' : "Nauru",
        'NPL' : "Nepal",
        'NLD' : "Netherlands",
        'NZL' : "New Zealand",
        'NIC' : "Nicaragua",
        'NER' : "Niger",
        'NGA' : "Nigeria",
        'MKD' : "North Macedonia",
        'NOR' : "Norway",
        'OMN' : "Oman",
        'PAK' : "Pakistan",
        'PLW' : "Palau",
        'PAN' : "Panama",
        'PNG' : "Papua New Guinea",
        'PRY' : "Paraguay",
        'PER' : "Peru",
        'PHL' : "Philippines",
        'POL' : "Poland",
        'PRT' : "Portugal",
        'QAT' : "Qatar",
        'ROU' : "Romania",
        'RUS' : "Russian Federation",
        'RWA' : "Rwanda",
        'KNA' : "Saint Kitts and Nevis",
        'LCA' : "Saint Lucia",
        'VCT' : "Saint Vincent and the Grenadines",
        'WSM' : "Samoa",
        'SMR' : "San Marino",
        'STP' : "Sao Tome and Principe",
        'SAU' : "Saudi Arabia",
        'SEN' : "Senegal",
        'SRB' : "Serbia",
        'SYC' : "Seychelles",
        'SLE' : "Sierra Leone",
        'SGP' : "Singapore",
        'SVK' : "Slovakia",
        'SVN' : "Slovenia",
        'SLB' : "Solomon Islands",
        'SOM' : "Somalia",
        'ZAF' : "South Africa",
        'SSD' : "South Sudan",
        'ESP' : "Spain",
        'LKA' : "Sri Lanka",
        'SDN' : "Sudan",
        'SUR' : "Suriname",
        'SWE' : "Sweden",
        'CHE' : "Switzerland",
        'SYR' : "Syrian Arab Republic",
        'TJK' : "Tajikistan",
        'TZA' : "Tanzania",
        'THA' : "Thailand",
        'TLS' : "Timor-Leste",
        'TGO' : "Togo",
        'TON' : "Tonga",
        'TTO' : "Trinidad and Tobago",
        'TUN' : "Tunisia",
        'TUR' : "Turkey",
        'TKM' : "Turkmenistan",
        'TUV' : "Tuvalu",
        'UGA' : "Uganda",
        'UKR' : "Ukraine",
        'ARE' : "United Arab Emirates",
        'GBR' : "United Kingdom",
        'USA' : "United States of America",
        'URY' : "Uruguay",
        'UZB' : "Uzbekistan",
        'VUT' : "Vanuatu",
        'VEN' : "Venezuela",
        'VNM' : "Viet Nam",
        'YEM' : "Yemen",
        'ZMB' : "Zambia",
        'ZWE' : "Zimbabwe",
      },
      'TC' : "Total cases",
      'NC' : "New cases",
      'TCPM' : "Cases per milion",
      'MODE' : "Choose the map mode",
      'INFO' : 'About us',
      'US' : 'Miłosz Wardyła - creative director\nIgor Urbanik - coder\nMateusz Konieczny - artist',
      'HH' : 'App made for the HackHeroes 2020 project.',
      'TIP' : 'Tips',
      'TIP1' : "Remember to wear a mask in public places according to your country's healthcare recommondations. The mask will lower others' probability of infection if you happen to have the virus. Don't forget to cover both your mouth and your nose!",
      'TIP2' : "Disinfecting hands is very improtant, because we often unknowingly touch a lot of different surfaces in shops, parks etc. and nobody knows who had touched them before. So remember to disinfect them both when you are doing something outside and when you simply come back to home.",
      'TIP3' : "One cannot forget about the proper hands washing. 20-30 seconds is enough to remove most of the viruses and bacteria from your hands and reduce the risk of infection.",
      'TIP4' : "Use credit card instead of cash in shops, restaurants etc. By doing so you avoid unnecessary contant and lower the chances of infection.",
      'TIP5' : "During the times of the pandemic try not to leave the house unless it is necessary. Avoid large groups of people and parties. For your's and others' sake: Stay home!",
      'TIP6' : "Maintain distance of at least 2 meters (or 6 feet) from other people when you are in public places or transport. By doing so you lower the risk of spreading the virus.",
      'TIP1T' : 'Mask',
      'TIP2T' : 'Hand disinfection',
      'TIP3T' : 'Washing hands',
      'TIP4T' : 'Cashless means better',
      'TIP5T' : 'Stay home, save lives',
      'TIP6T' : 'Social distancing',
      'DATA' : 'Data provided by Our World In Data',

    },
};
}